// const products = [
//   {
//     id: 1,
//     name: "Classic T-Shirt",
//     price: 650,
//     category: "Men",
//     inStock: true,
//     image: "./productImg/hoodi.jpg",
//   },
//   {
//     id: 2,
//     name: "Premium Hoodie",
//     price: 1200,
//     category: "Men",
//     inStock: true,
//     image: "./productImg/hoodi.jpg",
//   },
//   {
//     id: 3,
//     name: "Running Shoes",
//     price: 1800,
//     category: "Shoes",
//     inStock: false,
//     image: "./productImg/shoes.jpg",
//   },
//   {
//     id: 4,
//     name: "Casual Shirt",
//     price: 850,
//     category: "Men",
//     inStock: true,
//     image: "./productImg/shirt.jpg",
//   },
//   {
//     id: 3,
//     name: "Running Shoes",
//     price: 1800,
//     category: "Shoes",
//     inStock: false,
//     image: "./productImg/shoes.jpg",
//   },
//   {
//     id: 4,
//     name: "Casual Shirt",
//     price: 850,
//     category: "Men",
//     inStock: true,
//     image: "./productImg/shirt.jpg",
//   },
//   {
//     id: 3,
//     name: "Running Shoes",
//     price: 1800,
//     category: "Shoes",
//     inStock: false,
//     image: "./productImg/shoes.jpg",
//   },
//   {
//     id: 4,
//     name: "Casual Shirt",
//     price: 850,
//     category: "Men",
//     inStock: true,
//     image: "./productImg/shirt.jpg",
//   },
//   {
//     id: 3,
//     name: "Running Shoes",
//     price: 1800,
//     category: "Shoes",
//     inStock: false,
//     image: "./productImg/shoes.jpg",
//   },
//   {
//     id: 4,
//     name: "Casual Shirt",
//     price: 850,
//     category: "Men",
//     inStock: true,
//     image: "./productImg/shirt.jpg",
//   },
//   {
//     id: 3,
//     name: "Running Shoes",
//     price: 1800,
//     category: "Shoes",
//     inStock: false,
//     image: "./productImg/shoes.jpg",
//   },
//   {
//     id: 4,
//     name: "Casual Shirt",
//     price: 850,
//     category: "Men",
//     inStock: true,
//     image: "./productImg/shirt.jpg",
//   },
//   {
//     id: 3,
//     name: "Running Shoes",
//     price: 1800,
//     category: "Shoes",
//     inStock: false,
//     image: "./productImg/shoes.jpg",
//   },
//   {
//     id: 4,
//     name: "Casual Shirt",
//     price: 850,
//     category: "Men",
//     inStock: true,
//     image: "./productImg/shirt.jpg",
//   },
//   {
//     id: 3,
//     name: "Running Shoes",
//     price: 1800,
//     category: "Shoes",
//     inStock: false,
//     image: "./productImg/shoes.jpg",
//   },
//   {
//     id: 4,
//     name: "Casual Shirt",
//     price: 850,
//     category: "Men",
//     inStock: true,
//     image: "./productImg/shirt.jpg",
//   },
//   {
//     id: 3,
//     name: "Running Shoes",
//     price: 1800,
//     category: "Shoes",
//     inStock: false,
//     image: "./productImg/shoes.jpg",
//   },
//   {
//     id: 4,
//     name: "Casual Shirt",
//     price: 850,
//     category: "Men",
//     inStock: true,
//     image: "./productImg/shirt.jpg",
//   },
//   {
//     id: 3,
//     name: "Running Shoes",
//     price: 1800,
//     category: "Shoes",
//     inStock: false,
//     image: "./productImg/shoes.jpg",
//   },
//   {
//     id: 4,
//     name: "Casual Shirt",
//     price: 850,
//     category: "Men",
//     inStock: true,
//     image: "./productImg/shirt.jpg",
//   },
//   {
//     id: 3,
//     name: "Running Shoes",
//     price: 1800,
//     category: "Shoes",
//     inStock: false,
//     image: "./productImg/shoes.jpg",
//   },
//   {
//     id: 4,
//     name: "Casual Shirt",
//     price: 850,
//     category: "Men",
//     inStock: true,
//     image: "./productImg/shirt.jpg",
//   },
//   {
//     id: 4,
//     name: "Shoes",
//     price: 1850,
//     category: "Men",
//     inStock: true,
//     image: "./productImg/shoes2.jpg",
//   }
// ];



const products = [
  // ==================== MEN ====================
  {
    id: 1,
    name: "Classic T-Shirt",
    price: 650,
    category: "Men",
    inStock: true,
    image: "./productImg/men-tshirt.jpg",
  },
  {
    id: 2,
    name: "Premium Polo Shirt",
    price: 850,
    category: "Men",
    inStock: true,
    image: "./productImg/men-polo.jpg",
  },
  {
    id: 3,
    name: "Slim Fit Shirt",
    price: 1200,
    category: "Men",
    inStock: false,
    image: "./productImg/men-shirt.jpg",
  },

  // ==================== WOMEN ====================
  {
    id: 4,
    name: "Elegant Kurti",
    price: 1100,
    category: "Women",
    inStock: true,
    image: "./productImg/women-kurti.jpg",
  },
  {
    id: 5,
    name: "Casual Hijab",
    price: 450,
    category: "Women",
    inStock: true,
    image: "./productImg/women-hijab.jpg",
  },
  {
    id: 6,
    name: "Premium Abaya",
    price: 2200,
    category: "Women",
    inStock: false,
    image: "./productImg/women-abaya.jpg",
  },

  // ==================== KIDS ====================
  {
    id: 7,
    name: "Kids T-Shirt",
    price: 450,
    category: "Kids",
    inStock: true,
    image: "./productImg/kids-tshirt.jpg",
  },
  {
    id: 8,
    name: "Kids Panjabi",
    price: 750,
    category: "Kids",
    inStock: true,
    image: "./productImg/kids-panjabi.jpg",
  },
  {
    id: 9,
    name: "Kids Frock",
    price: 950,
    category: "Kids",
    inStock: false,
    image: "./productImg/kids-frock.jpg",
  },

  // ==================== SHOES ====================
  {
    id: 10,
    name: "Classic Sneakers",
    price: 1800,
    category: "Shoes",
    inStock: true,
    image: "./productImg/sneakers.jpg",
  },
  {
    id: 11,
    name: "Casual Loafers",
    price: 2200,
    category: "Shoes",
    inStock: true,
    image: "./productImg/loafers.jpg",
  },
  {
    id: 12,
    name: "Sports Shoes",
    price: 2500,
    category: "Shoes",
    inStock: false,
    image: "./productImg/sports-shoes.jpg",
  },

  // ==================== PERFUME ====================
  {
    id: 13,
    name: "Oud Premium",
    price: 1800,
    category: "Perfume",
    inStock: true,
    image: "./productImg/oud.jpg",
  },
  {
    id: 14,
    name: "Arabian Musk",
    price: 1500,
    category: "Perfume",
    inStock: true,
    image: "./productImg/musk.jpg",
  },
  {
    id: 15,
    name: "Royal Amber",
    price: 2200,
    category: "Perfume",
    inStock: false,
    image: "./productImg/amber.jpg",
  },
];


export default products;